py runner.py G 1 
py runner.py S 1
py runner.py G 2
py runner.py S 2
py runner.py G 3 
py runner.py S 3
py runner.py G 4 
py runner.py S 4
py runner.py G 5 
py runner.py S 5
py runner.py G 6 
py runner.py S 6
py runner.py G 7 
py runner.py S 7
py runner.py G 8 
py runner.py S 8
py runner.py G 9 
py runner.py S 9
py runner.py G 10
py runner.py S 10
py runner.py G 20
py runner.py S 20
